export const MISSING_COUNTRY_VARIABLE_ERROR =
  'Missing environment variable: COUNTRY';
export const MISSING_ENVIRONMENT_VARIABLE_ERROR =
  'Missing environment variable: ENVIRONMENT';
export const MISSING_ACCOUNT_VARIABLE_ERROR =
  'Missing environment variable: ACCOUNT';
export const MISSING_REGION_VARIABLE_ERROR =
  'Missing environment variable: REGION';
export const MISSING_ORGANISATION_NAME_ERROR =
'Missing environment variable: ORGANISATION_NAME';
export const MISSING_CEDAR_LAMBDA_LAYER_ARN_ERROR =
'Missing environment variable: CEDAR_LAMBDA_LAYER_ARN';
